### ISSUE TITLE
Add-on not connecting to Valispace

### ISSUE THREAD

**Issue by Gabrielgut98** [valispace/ValispaceExcelPlugin#2]
Hi, thank you beforehand for your time,

The first time I downloaded the plugin it worked well. Even tho I gave the permission to the folder, after the first time I have not been able to link the Excel sheet to my Vali workspace. I have tried downloading again, changing the folder and even the plugin name; but nothing seems to work. 

![Immagine 2022-03-04 113944](https://user-images.githubusercontent.com/100930253/156748460-7fddcc7f-a593-433f-82f2-9382d50902e0.png)

Other computers from my company are able to access the workspace with the plugin, so the issue is local. Can you help me?

**Comment by franciscoatsantos** [comment]
Hi @Gabrielgut98 , thank you for making us aware of the problem, however I would kindly ask you to get in contact with the [valispace support team](support@valispace.com)

**Comment by cauenapier** [comment]
This issue was happening when you have a "/" at the end of the url. Removing it manually would fix this issue.
But a check has been added to the addon now, so this won't happen anymore.
